apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: madhupdevops/backend-wanderlust:v2
          env:
            - name: MONGODB_URI
              value: mongodb://mongo-service:27017/wanderlust
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec: 
  ports:
  - port: 5000
    protocol: TCP
  type: ClusterIP
  selector:
    app: backend
