apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    database: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      database: mongodb
  template:
    metadata:
      labels:
        database: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
    volumeMounts:
          - name: mongo-volume
            mountPath: /data/db
  volumes: 
  - name: mongo-volume
    persistentVolumeClaim:
      claimName: mongo-volume-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    database: mongodb
  ports:
    - port: 27017
      targetPort: 27017
